# Use the official Node.js image as the base image
FROM node:18.17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the port that the app will run on
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev"]